floorTiles = layer_tilemap_get_id("FloorTiles")
wallTiles = layer_tilemap_get_id("WallTiles")
xSpeed = 0
xSpeedLimit = 8
ySpeed = 0
ySpeedLimit = 10
jumpStr = 8
accel = 1
grav = 0.3
allTiles = [floorTiles,wallTiles]
lockedMvt = 0
death = false
onWall = 0
onGround = false
spritesArray = [sPlayerAir, sPlayerRun, sPlayerDeath, sPlayerIdle, sPlayerWallHold]
sNumber = -1